<a href="https://colab.research.google.com/github/javoocodeando/DSND_Term2/blob/master/Chapter_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
%tensorflow_version 2.x

In [ ]:
import tensorflow as tf
print("GPU Available: ", tf.test.is_gpu_available())

GPU Available:  True


In [ ]:
print(tf.__version__)

2.7.0


In [ ]:
from tensorflow import keras

print(tf.keras.__version__)

2.7.0


In [1]:
help()



Welcome to Python 3.7's help utility!

If this is your first time using Python, you should definitely check out
the tutorial on the Internet at https://docs.python.org/3.7/tutorial/.

Enter the name of any module, keyword, or topic to get help on writing
Python programs and using Python modules.  To quit this help utility and
return to the interpreter, just type "quit".

To get a list of available modules, keywords, symbols, or topics, type
"modules", "keywords", "symbols", or "topics".  Each module also comes
with a one-line summary of what it does; to list the modules whose name
or summary contain a given string such as "spam", type "modules spam".

help> sum
Help on built-in function sum in module builtins:

sum(iterable, start=0, /)
    Return the sum of a 'start' value (default: 0) plus an iterable of numbers
    
    When the iterable is empty, return the start value.
    This function is intended specifically for use with numeric values and may
    reject non-numeric types.


Y

In [2]:
dir(str)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmod__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'capitalize',
 'casefold',
 'center',
 'count',
 'encode',
 'endswith',
 'expandtabs',
 'find',
 'format',
 'format_map',
 'index',
 'isalnum',
 'isalpha',
 'isascii',
 'isdecimal',
 'isdigit',
 'isidentifier',
 'islower',
 'isnumeric',
 'isprintable',
 'isspace',
 'istitle',
 'isupper',
 'join',
 'ljust',
 'lower',
 'lstrip',
 'maketrans',
 'partition',
 'replace',
 'rfind',
 'rindex',
 'rjust',
 'rpartition',
 'rsplit',
 'rstrip',
 'split',
 'splitlines',
 'startswith',
 'strip',
 'swapcase',
 'title',
 'translate',
 'upper',


In [3]:
dir(sum)

['__call__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__name__',
 '__ne__',
 '__new__',
 '__qualname__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__self__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__text_signature__']

In [5]:
from random import randint
randomint = randint(1, 100)
print(randomint)

75


In [6]:
import random
randomint = random.randint(1, 100)
print(randomint)

16


In [8]:
IntegerVar = 10
IntegerVar += 10
print(IntegerVar)

20


In [11]:
StringVar = "Deep"
StringVar += " Learning"
print(StringVar)

Deep Learning


In [12]:
IntegerVar, StringVar = StringVar, IntegerVar

In [13]:
print(IntegerVar)

Deep Learning


In [14]:
print(StringVar)

20


In [15]:
a = 20
if a >=22:
  print("Paris")
elif a<=21:
  print("Barcelona")


Barcelona


In [16]:
b=1
print("Paris" if b >= 92 else "Barcelona")

Barcelona


In [17]:
def mi_universidad(universidad = "UPC"):
  y = "Mi universidad es la " + universidad
  return (y)

print(mi_universidad("UPM"))
print(mi_universidad(universidad = "UPV")) #Buena Practica usar el nombre de la
                                            #variable
print(mi_universidad())


Mi universidad es la UPM
Mi universidad es la UPV
Mi universidad es la UPC


In [18]:
def foo():
  a, b = 4, 5
  return a, b
foo()

(4, 5)

In [19]:
fibonacci = (lambda x:1 if x <= 2 else
             fibonacci(x-1) + fibonacci(x-2))

fibonacci(10)

55

In [2]:
class Calculadora(object):
  """Clase de una calculadora"""

  def __init__(self):
    """Inicializa la clase Calculadora"""
    self.valor = 0
  
  def suma(self, n):
    """Suma un numero n al valor"""
    self.valor += n

  def getValor(self):
    """Obtiene el valor"""
    return self.valor

In [4]:
calc = Calculadora()
calc.suma(2)
print(calc.getValor())


2


In [5]:
calc.suma(2)
print(calc.getValor())

4


In [6]:
vec = [1, 2, 3]
it = iter(vec)

next(it)

1

In [8]:
next(it)

3

In [9]:
type(vec)

list

In [10]:
type(it)

list_iterator

In [11]:
#Decoradores

In [12]:
def voy_a_imprimir_Hola():
  print("Hola")

voy_a_imprimir_Hola()

Hola


In [13]:
def voy_a_imprimir_Hola():
  print("Hola")

def my_decorator(func):
  def wrapper():
    print("[Aviso: voy a decir algo]")
    func()
    print("[Aviso: ya he dicho algo]")
  return wrapper

voy_a_imprimir_Hola = my_decorator(voy_a_imprimir_Hola)

voy_a_imprimir_Hola()

[Aviso: voy a decir algo]
Hola
[Aviso: ya he dicho algo]


In [14]:
voy_a_imprimir_Hola = my_decorator(voy_a_imprimir_Hola)

In [15]:
@my_decorator
def voy_a_imprimir_Hola():
  print("Hola")

In [16]:
voy_a_imprimir_Hola()

[Aviso: voy a decir algo]
Hola
[Aviso: ya he dicho algo]


In [18]:
import numpy as np

x = np.array(8)
print("x: ", x)
print("x ndim: ", x.ndim)
print("x shape: ", x.shape)
print("x size: ", x.size)
print("x dtype: ", x.dtype)


x:  8
x ndim:  0
x shape:  ()
x size:  1
x dtype:  int64


In [19]:
x = np.array([2.3, 4.2, 3.3, 1.8])
print("x: ", x)
print("x ndim: ", x.ndim)
print("x shape: ", x.shape)
print("x size: ", x.size)
print("x dtype: ", x.dtype) # notice the float datatype


x:  [2.3 4.2 3.3 1.8]
x ndim:  1
x shape:  (4,)
x size:  4
x dtype:  float64


In [23]:
x = np.array([[1,2,3], [4,5,6], [7,8,9]])
print("x:\n", x)
print("x ndim: ", x.ndim)
print("x shape: ", x.shape)
print("x size: ", x.size)
print("x dtype: ", x.dtype)


x:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
x ndim:  2
x shape:  (3, 3)
x size:  9
x dtype:  int64


In [24]:
x = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])
print("x:\n", x)
print("x ndim: ", x.ndim)
print("x shape: ", x.shape)
print("x size: ", x.size)
print("x dtype: ", x.dtype)


x:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
x ndim:  3
x shape:  (2, 2, 2)
x size:  8
x dtype:  int64


In [25]:
print("np.zeros((3,3)):\n", np.zeros((3,3)))
print("np.ones((3,3)):\n", np.ones((3,3)))
print("np.eye((3)): (identity matrix)\n", np.eye((3)))
print("np.random.random((3,3)):\n", np.random.random((3,3)))

np.zeros((3,3)):
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
np.ones((3,3)):
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
np.eye((3)): (identity matrix)
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
np.random.random((3,3)):
 [[0.75353231 0.49534734 0.67656421]
 [0.33307333 0.91839135 0.18775961]
 [0.70187752 0.90397234 0.49264983]]


In [4]:
import numpy as np

x = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(x)
print("x column 1: ", x[:, 1])
print("x row 0: ", x[0, :])
print("x rows 0,1 & cols 1,2: \n", x[0:2, 1:3])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
x column 1:  [ 2  6 10]
x row 0:  [1 2 3 4]
x rows 0,1 & cols 1,2: 
 [[2 3]
 [6 7]]


In [6]:
a = np.array([[1,2,3], [4,5,6]], dtype=np.int32)
b = np.array([[7,8], [9,10], [11,12]], dtype=np.int32)
c = a.dot(b)
print (f"{a.shape} * {b.shape} = {c.shape}")
print(c)

(2, 3) * (3, 2) = (2, 2)
[[ 58  64]
 [139 154]]


In [7]:
x = np.array([[1,2,3,4,5,6]])
print(x)
print("x.shape: ", x.shape)
y = np.reshape(x, (2,3))
print("y: \n", y)
print("y.shape: ", y.shape)
z = np.reshape(x, (2, -1))
print("z: \n", z)
print("z.shape: ", z.shape)

[[1 2 3 4 5 6]]
x.shape:  (1, 6)
y: 
 [[1 2 3]
 [4 5 6]]
y.shape:  (2, 3)
z: 
 [[1 2 3]
 [4 5 6]]
z.shape:  (2, 3)


In [8]:
x = np.array([[1,2,3], [4,5,6]])
print("x: \n", x)
print("x.shape: ", x.shape)
y = np.expand_dims(x, 1)
print("y: \n", y)
print("y.shape: ", y.shape)


x: 
 [[1 2 3]
 [4 5 6]]
x.shape:  (2, 3)
y: 
 [[[1 2 3]]

 [[4 5 6]]]
y.shape:  (2, 1, 3)


In [9]:
x = np.array([[[1,2,3]], [[4,5,6]]])
print("x: \n", x)
print("x.shape: ", x.shape)
y = np.squeeze(x, 1) #squeeze dim 1
print("y: \n", y)
print("y.shape: ", y.shape)

x: 
 [[[1 2 3]]

 [[4 5 6]]]
x.shape:  (2, 1, 3)
y: 
 [[1 2 3]
 [4 5 6]]
y.shape:  (2, 3)


In [11]:
x = np.array([[1,2,3,4,5,6]])
print(x)

print(np.argmax(x))
print(np.max(x))

[[1 2 3 4 5 6]]
5
6


In [12]:
x = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(x)
print(np.argmax(x))
print(np.max(x))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
11
12


In [13]:
print(np.argmax(x, axis=0))
print(np.max(x, axis=0))

print(np.argmax(x, axis=1))
print(np.max(x, axis=1))

[2 2 2 2]
[ 9 10 11 12]
[3 3 3]
[ 4  8 12]
